### ISSUE TITLE
Support query and metadata retrieval from legacy origin servers

### ISSUE THREAD

**Issue by bashallc** [clindatsci/dicomweb-client#11]
Im getting a JSONDECODE error when trying to use the QIDO against a dicom rs broker (dicomweb -> dicom)

Using the requests module in python if i change the header "Accept : application/json" i am able to get a response  but the server i am calling with dicomweb-client throws the error "application/json+dicom" is not accepted 

Is there a way to change the header (similar to how the requests module can) from application/json+dicom to just application/json ?

**Comment by hackermd** [comment]
It seems you are interacting with an older implementation of the standard. The media type used to be `application/json` instead of `application/json+dicom` in earlier editions.

It think it's a good idea to allow clients to specify the media type for query (search for) methods similar to retrieve methods to enable backwards compatibility with older servers. I renamed the issue accordingly.

**Comment by bashallc** [comment]
Thanks @hackermd that is perfect! As you would expect in healthcare there are a number of older applications running which may take awhile to update

**Comment by hackermd** [comment]
@bashallc I implemented this functionality in branch [feature/application-json](https://github.com/clindatsci/dicomweb-client/tree/application-json). Could you please test whether that works with your origin server?

```python
from dicomweb_client.api import DICOMwebClient

client = DICOMwebClient(...)
client.search_for_studies()
``` 

Note that the media type does not need to be specified. The client negotiates the content type by using the following header for the request message: `Accept: application/dicom+json, application/json`. The server can then respond with the content type that it supports.

**Comment by bashallc** [comment]
@hackermd i pulled the branch but im getting the same result - throwing an error. Seems to be ignoring the header change even when you manually add the accept conditions

Note  - Using the requests module it works correct;ly.

The target is the dicom-RS broker (converts dicomweb queries  - > DIMSE) found at https://github.com/RSNA/dcmrs-broker

**Comment by hackermd** [comment]
Can you please try the following (replacing `<dicomweb-wado-rs>` with the URL of WADO-RS):

```none
curl --verbose -H 'Accept: application/dicom+json, application/json' -I <dicomweb-wado-rs>/studies
```

**Comment by bashallc** [comment]
<dicomweb-wado-rs> = http://10.17.90.161:4567/qido-rs

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0* Could not resolve host: application
curl: (6) Could not resolve host: application
* Found bundle for host application: 0x65ccb0 [serially]
* Server doesn't support multiplex (yet)
* Connection #0 is still name resolving, can't reuse

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* Could not resolve host: application
curl: (6) Could not resolve host: application
*   Trying 10.17.90.161:4567...
* TCP_NODELAY set
* Connected to 10.17.90.161 (10.17.90.161) port 4567 (#2)
> HEAD /qido-rs/studies HTTP/1.1

> Host: 10.17.90.161:4567

> User-Agent: curl/7.65.3

> Accept: */*

> 

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK

< Date: Fri, 02 Aug 2019 06:27:06 GMT

< Content-Type: text/html;charset=utf-8

< Transfer-Encoding: chunked

< Server: Jetty(9.4.4.v20170414)

< 


  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Date: Fri, 02 Aug 2019 06:27:06 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Server: Jetty(9.4.4.v20170414)


* Connection #2 to host 10.17.90.161 left intact

**Comment by bashallc** [comment]
@hackermd this can be closed - I shouldn't be using older software - ive solved this by using a standalone dcm4che-arc 5 instance which fully supports QIDO / WADO
