### ISSUE TITLE
QIDO Authentication via token

### ISSUE THREAD

**Issue by bashallc** [clindatsci/dicomweb-client#15]
Secure versions of dcm4che arc 5 use keycloak for authentication for both UI and webservices. Can other auth methods be used other than basic auth in DICOMweb-client? In particular client id / token

Thanks
Chris

**Comment by ntenenz** [comment]
Nearly any authn protocol supported by the `requests` package should be compatible using the `auth` parameter in `DICOMwebClient.__init__`. See [this commit](https://github.com/clindatsci/dicomweb-client/commit/1b18dc40e4e8559ad2cb25d0bbe2ce8d7570d088) from a few months back.

**Comment by hackermd** [comment]
The constructor of `DICOMwebClient` also accepts a `header` keyword argument, which allows you to include custom headers (such as a token) into request messages.

**Comment by bashallc** [comment]
Thanks @hackermd i must be constructing the parameters incorrectly:

I still get a 401 refused connection but if i use a normal requests command it works
Doesnt Work:
client = DICOMwebClient(url="http://<myip>:8080/dcm4chee-arc/aets/QEPACS4/rs",
                        headers={"access_token":token})
Works:

url = "http://10.17.4.154:8080/dcm4chee-arc/aets/QEPACS4/rs/studies"

querystring = {"PatientID":"*","access_token":token}
headers = {}
response = requests.request("GET", url, headers=headers, params=querystring)

Any ideas what im doing wrong?

**Comment by bashallc** [comment]
Thanks @hackermd i must be constructing the parameters incorrectly:

I still get a 401 refused connection but if i use a normal requests command it works

Doesnt Work:
client = DICOMwebClient(url="http://:8080/dcm4chee-arc/aets/QEPACS4/rs",
headers={"access_token":token})
Works:

url = "http://:8080/dcm4chee-arc/aets/QEPACS4/rs/studies"

querystring = {"PatientID":"*","access_token":token}
headers = {}
response = requests.request("GET", url, headers=headers, params=querystring)

Any ideas what im doing wrong?

**Comment by bashallc** [comment]
Thanks @hackermd i must be constructing the parameters incorrectly:

I still get a 401 refused connection but if i use a normal requests command it works
Doesnt Work:
client = DICOMwebClient(url="http://myip:8080/dcm4chee-arc/aets/QEPACS4/rs",
headers={"access_token":token})
Works:

url = "http://myip:8080/dcm4chee-arc/aets/QEPACS4/rs/studies"

querystring = {"PatientID":"*","access_token":token}
headers = {}
response = requests.request("GET", url, headers=headers, params=querystring)

Any ideas what im doing wrong?

**Comment by bashallc** [comment]
Solved - example for others below

client = DICOMwebClient(url="http://myip:8080/dcm4chee-arc/aets/QEPACS4/rs",
                        headers={'Authorization': 'Bearer ' + tokens['access_token']})

**Comment by hackermd** [comment]
@bashallc glad you figured it out. I added your example to the [user guide](https://github.com/clindatsci/dicomweb-client/blob/master/docs/usage.rst) section of the API documentation.
