### ISSUE TITLE
Open alternatives to https://dicomcloud.azurewebsites.net

### ISSUE THREAD

**Issue by nordlow** [clindatsci/dicomweb-client#4]
Are there any open demo servers other than `https://dicomcloud.azurewebsites.net`?

As a follow up to https://github.com/clindatsci/dicomweb-client/issues/3#issuecomment-419660085 because I'm developing course material that depends on the availability of a server providing a complete tree of DICOM studies-series-instances-frames without any missing links (in the case for https://dicomcloud.azurewebsites.net most series are missing).

**Comment by ntenenz** [comment]
Hi @nordlow, one surefire solution would be be to personally setup an instance of [Orthanc](https://www.orthanc-server.com/) or [dcm4chee](https://www.dcm4che.org/) with publicly available data. This may be easier than tracking down a reliable, publicly accessible DICOMweb server.
